version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-cart
    environment:
      MYSQL_ROOT_PASSWORD: Zsgs@2025
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  cart-api:
    build: .
    container_name: cart-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cart:3306/ecommerce_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Zsgs@2025

volumes:
  mysql-data:
